export const KNOWLEDGE_DOCUMENT_AUDIT_EVENTS = {
  SOURCE_CREATED: 'SOURCE_CREATED',
  SOURCE_UPDATED: 'SOURCE_UPDATED',
  SOURCE_DELETED: 'SOURCE_DELETED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  SECTIONS_REPLACED: 'SECTIONS_REPLACED',
  SNAPSHOT_RESTORED: 'SNAPSHOT_RESTORED',
} as const;
