import type { UserRole } from '@fosterhub/types';

export const permissionKeys = [
  'users.view',
  'users.manage',
  'roles.view',
  'roles.manage',
  'permissions.view',
  'cases.view.assigned',
  'cases.view.team',
  'cases.view.all',
  'cases.edit',
  'children.view',
  'children.edit',
  'intake.create',
  'intake.assign',
  'placements.manage',
  'requests.submit',
  'requests.review',
  'requests.approve',
  'messages.send',
  'messages.read',
  'vendors.view',
  'vendors.review',
  'vendors.approve',
  'reports.view',
  'audit.view',
  'organizations.view',
  'organizations.manage',
  'applications.view',
  'applications.manage',
  'surveys.view',
  'surveys.manage',
  'travel_approvals.review',
  'knowledge_sources.view',
  'knowledge_sources.manage',
] as const;

export type PermissionKey = (typeof permissionKeys)[number];

export const rolePermissionMap: Record<UserRole, PermissionKey[]> = {
  admin: [...permissionKeys],
  manager: [
    'roles.view',
    'permissions.view',
    'cases.view.team',
    'cases.view.all',
    'cases.edit',
    'children.view',
    'children.edit',
    'intake.create',
    'intake.assign',
    'placements.manage',
    'requests.review',
    'requests.approve',
    'messages.send',
    'messages.read',
    'vendors.view',
    'vendors.review',
    'reports.view',
    'audit.view',
  ],
  worker: [
    'cases.view.assigned',
    'cases.edit',
    'children.view',
    'children.edit',
    'intake.create',
    'requests.submit',
    'requests.review',
    'messages.send',
    'messages.read',
    'vendors.view',
  ],
  resource_parent: [
    'children.view',
    'requests.submit',
    'messages.send',
    'messages.read',
    'vendors.view',
  ],
  vendor: [
    'messages.read',
    'messages.send',
    'vendors.view',
  ],
  birth_parent: [
    'messages.read',
    'messages.send',
    'children.view',
  ],
  youth: [
    'messages.read',
    'messages.send',
    'requests.submit',
  ],
  state_super_admin: [
    'users.view',
    'users.manage',
    'roles.view',
    'permissions.view',
    'cases.view.all',
    'children.view',
    'requests.review',
    'requests.approve',
    'vendors.view',
    'vendors.review',
    'vendors.approve',
    'reports.view',
    'audit.view',
    'organizations.view',
    'organizations.manage',
    'applications.view',
    'applications.manage',
    'surveys.view',
    'surveys.manage',
    'travel_approvals.review',
    'knowledge_sources.view',
    'knowledge_sources.manage',
  ],
  county_admin: [
    'users.view',
    'users.manage',
    'roles.view',
    'permissions.view',
    'cases.view.team',
    'cases.view.all',
    'cases.edit',
    'children.view',
    'children.edit',
    'requests.review',
    'requests.approve',
    'vendors.view',
    'vendors.review',
    'applications.view',
    'applications.manage',
    'surveys.view',
    'travel_approvals.review',
    'reports.view',
    'knowledge_sources.view',
    'knowledge_sources.manage',
  ],
  licensing_worker: [
    'children.view',
    'intake.create',
    'requests.submit',
    'messages.send',
    'messages.read',
    'applications.view',
    'applications.manage',
    'surveys.view',
    'vendors.view',
  ],
};

export function getRolePermissions(role: UserRole): PermissionKey[] {
  return rolePermissionMap[role] ?? [];
}

export function hasPermission(role: UserRole, permission: PermissionKey): boolean {
  return getRolePermissions(role).includes(permission);
}
